version: '3.8'

services:
  yard-management-system:
    build: .
    ports:
      - "8094:8094"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGODB_URI=mongodb://mongodb:27017/yard_management_system
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - paklog-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - paklog-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - paklog-network

networks:
  paklog-network:
    driver: bridge